version: '3.8'

networks:
  kafka-net:
    driver: bridge

services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    environment:
      - 'ALLOW_ANONYMOUS_LOGIN=yes'
    ports:
      - '2181:2181'
    networks:
      - kafka-net
  kafka:
    image: 'bitnami/kafka:latest'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
    ports:
      - "9092:9092"
    networks:
      - kafka-net
    depends_on:
      - zookeeper
  kafka-exporter:
    image: "bitnami/kafka-exporter:latest"
    ports:
      - "9308:9308"
    command:
      - --kafka.server=kafka:9092
    networks:
      - kafka-net

#services:
#  zookeeper:
#    container_name: blockchain-zookeeper
#    image: bitnami/zookeeper
#    networks:
#      - kafka-net
#    ports:
#      - '2181:2181'
#    environment:
#      - ALLOW_ANONYMOUS_LOGIN=yes
#
#  kafka:
#    container_name: blockchain-kafka
#    image: bitnami/kafka
#    networks:
#      - kafka-net
#    ports:
#      - '9092:9092'
#    environment:
#      - KAFKA_BROKER_ID=1
#      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
#      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
#      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
#      - ALLOW_PLAINTEXT_LISTENER=yes
#    depends_on:
#      - zookeeper