spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mysql?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 1234
  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  profiles:
    include: core

server:
  port: 8080